# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7cb91e16bf8101c22ad256559e95fe39bf529926b918ab9a59b48b5c91fc7d26d0d265dbfa4164c949e16ebb46d6f698e21730cea29b2c94c18bb0a158ebf9c

test:
  secret_key_base: 4ae0c0deab9a652c1157088e7afc7b6488d032c61548cbf3b58086799f573b38d8e05c8a0191f35414884f87dae09570f1ba9424e22a0f46569687c825556542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
