# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ad73d7547b467b2a291112f184e32bb0c35f4d826a3aba29a48929d5aafe30a63398b3421815069a8f9b584169856af04756a0f04461b27b6045141efa2eb74

test:
  secret_key_base: 2622491c14fd8ca05856590b91f295c6508b38a030e0fdcc49ce533f2adbff27c32aa4f240afefb5daaf831ac090c5906af46933d9f855186b7c09b0e4a7202b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
