# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e0b5013ca85358364032647ecd456023b9b361c250ee8024b193c76f1de22fee36fb453673d5b37a8b71380783ae486456e7f900185d5505c00bcb8c1a96f81

test:
  secret_key_base: 5e0f867dbfea703117254953acc3257c5cec57b1952b20e09e5fc3367c03f1f7f60760c6ae5a0b20d072c2396758128c32f1395814e2a4c0bfeaa493d7a2f082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
