# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 125484a19bf959fbcc9c0bccf07f26cb73157d00764646abc9e15030d106ac3100b116072aba9cc35f42a14cf611d4abe0a3dac2c9dc0c1ba75b197cbc0aef65

test:
  secret_key_base: f6925c160df14f1acdc011039d9afac15ee2043fcb3a3adaabf44dd07a2151924d66ffb3da6f6751d8aeb48a689141c9ce23f05e9e35a1ecbefdfef71a32b5f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
