# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8500d8a2bac9f66cff7c792137029de5310ac9ed82ba5b91c882e1f82e4897e4c456138f7fa8afcb9aa8af8b2d7f8c55687bdb6c484e19fa6eebb157b82943

test:
  secret_key_base: 1978e9847aea008cf7b54fc058768867fc3f8a192a39fcfeb8f432a13fe0baaa7a8dd373b399b753d9a31eb42004fae3fe5332ff1078efda4419a083a30ced79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
