# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b9adb19ae406f92d390afa6ebf1d376034e298a14e495da62a5648ee2b9bee87660e322dc246fbf02090c828fbe587f5f0b702e63f4035a8147aa93b09b1bb

test:
  secret_key_base: 1730a9992b7512e710cb1a20e1cfa11940bbeb140d53fa4bc5d42d7d6ca8a7a94b9941aeb2b66f393681a50d345e52f501395ff56fa6ee820c40b19823dd15d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
